name = "sg-psle"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./public"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "dwolf-psle"
database_id = "c8c48497-557c-408f-953f-be70d225d13a"
